greeting:
  message: "hello"

quarkus:
# H2 SQL db settings
  datasource:
    jdbc:
      driver: org.h2.Driver
      url: jdbc:h2:mem:myDB;mode=MSSQLServer #INIT=CREATE DOMAIN IF NOT EXISTS UNIQUEIDENTIFIER AS UUID;   #;mode=MSSQLServer
    username: sa
    db-kind: mssql
# MS SQL Server settings --- See readme.md how to start and setup sql server container
#  datasource:
#    jdbc:
#      url: jdbc:sqlserver://localhost:1433;databaseName=myDB
#    username: sa
#    password: NiCe_pAsSword123*
#    db-kind: mssql
  flyway:
    migrate-at-start: true
    validate-on-migrate: false
